name: Notify Failures
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  slack-alert:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.workflow_run.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@unknown11-svg Workflow failed! Please check [logs](${{ github.event.workflow_run.html_url }})"
            })