name: Test Report
on: 
  workflow_run:
    workflows: ["CI/CD"]
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Post Coverage Report
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.workflow_run.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `@team ✅ Tests passed with ${process.env.CODECOV_COVERAGE}% coverage`
            })